services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - plugins.security.disabled=true
      - plugins.security.ssl.transport.enabled=false
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_SECURITY_DEFAULT_ADMIN_USERNAME=admin
      - OPENSEARCH_SECURITY_DEFAULT_ADMIN_PASSWORD=a*3342567451kjhrlvjan*0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9201:9200
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://opensearch-node1:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  opensearch-node2:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - plugins.security.disabled=true
      - plugins.security.ssl.transport.enabled=false
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_SECURITY_DEFAULT_ADMIN_USERNAME=admin
      - OPENSEARCH_SECURITY_DEFAULT_ADMIN_PASSWORD=a*3342567451kjhrlvjan*0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    ports:
      - 9202:9200
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://opensearch-node2:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=findbeat
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file: '.env.local'
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
      opensearch-node1:
        condition: service_healthy
      opensearch-node2:
        condition: service_healthy
    volumes:
      - ./src:/app/src

volumes:
  opensearch-data1:
  opensearch-data2:
  db-data:
